apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-nginx
  template:
    metadata:
      labels:
        app: my-flask-nginx
    spec:
      containers:
      - name: flask-app
        image: haripofficial/flaskapi:latest
        ports:
        - containerPort: 8000
        - containerPort: 8001
